USE BOOK_STORE;

LOAD DATA INFILE '~/dev/assignments/DS5110/Project/Online-Book-Store/database/data/zipcode.csv'
INTO TABLE ZIPCODE
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA INFILE '~/dev/assignments/DS5110/Project/Online-Book-Store/database/data/Publisher.csv'
INTO TABLE PUBLISHER
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE '~/dev/assignments/DS5110/Project/Online-Book-Store/database/data/final_books.csv'
INTO TABLE BOOK
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE '~/dev/assignments/DS5110/Project/Online-Book-Store/database/data/Authors.csv'
INTO TABLE AUTHOR
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE '~/dev/assignments/DS5110/Project/Online-Book-Store/database/data/Author_ISBN.csv'
INTO TABLE AUTHOR_BOOK
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE '~/dev/assignments/DS5110/Project/Online-Book-Store/database/data/store.csv'
INTO TABLE STORE
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA INFILE '~/dev/assignments/DS5110/Project/Online-Book-Store/database/data/Store_Copies.csv'
INTO TABLE STORE_COPIES
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA INFILE '~/dev/assignments/DS5110/Project/Online-Book-Store/database/data/subscription.csv'
INTO TABLE SUBSCRIPTION
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE '~/dev/assignments/DS5110/Project/Online-Book-Store/database/data/customer.csv'
INTO TABLE CUSTOMER
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA INFILE '~/dev/assignments/DS5110/Project/Online-Book-Store/database/data/Genre.csv'
INTO TABLE GENRE
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA INFILE '~/dev/assignments/DS5110/Project/Online-Book-Store/database/data/Book_Genre.csv'
INTO TABLE BOOK_GENRE
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

