# Generated by Django 3.2.5 on 2022-11-14 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
